insert into public.categories (name, icon)
values
  ('Movies', 'clapperboard'),
  ('Science', 'flask-conical'),
  ('History', 'landmark'),
  ('Crypto', 'bitcoin'),
  ('Geography', 'globe'),
  ('General Knowledge', 'brain'),
  ('Technology', 'cpu'),
  ('Sports', 'trophy'),
  ('Food', 'utensils')
on conflict (name) do nothing;

insert into public.questions (
  category_id,
  difficulty,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_answer
)
select
  c.id,
  q.difficulty::public.difficulty_level,
  q.question_text,
  q.option_a,
  q.option_b,
  q.option_c,
  q.option_d,
  q.correct_answer::public.answer_option
from (
  values
    ('Geography', 'easy', 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C'),
    ('Geography', 'medium', 'Which desert is the largest hot desert in the world?', 'Gobi Desert', 'Sahara Desert', 'Kalahari Desert', 'Arabian Desert', 'B'),
    ('Geography', 'easy', 'Which is the longest river in the world?', 'Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River', 'B'),
    ('Geography', 'medium', 'Mount Kilimanjaro is located in which country?', 'Kenya', 'Tanzania', 'Ethiopia', 'Uganda', 'B'),
    ('Geography', 'easy', 'Which ocean is the largest?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D'),
    ('Geography', 'medium', 'Which country has the most population in the world?', 'India', 'USA', 'China', 'Indonesia', 'A'),
    ('Geography', 'easy', 'Which continent is known as the Dark Continent?', 'Asia', 'Africa', 'South America', 'Australia', 'B'),
    ('History', 'easy', 'Who was the first President of the United States?', 'Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams', 'B'),
    ('History', 'medium', 'In which year did World War II end?', '1942', '1945', '1939', '1950', 'B'),
    ('History', 'easy', 'Who discovered America in 1492?', 'Vasco da Gama', 'Christopher Columbus', 'Ferdinand Magellan', 'Marco Polo', 'B'),
    ('History', 'medium', 'The Great Wall of China was primarily built to protect against which group?', 'Mongols', 'Romans', 'Vikings', 'Huns', 'A'),
    ('History', 'easy', 'Who was known as the Iron Lady?', 'Angela Merkel', 'Margaret Thatcher', 'Indira Gandhi', 'Golda Meir', 'B'),
    ('History', 'medium', 'Which empire was ruled by Genghis Khan?', 'Roman Empire', 'Ottoman Empire', 'Mongol Empire', 'Persian Empire', 'C'),
    ('History', 'easy', 'In which country did the Renaissance begin?', 'France', 'Germany', 'Italy', 'Spain', 'C'),
    ('Science', 'easy', 'What planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B'),
    ('Science', 'medium', 'What is the speed of light in vacuum?', '300,000 km/s', '150,000 km/s', '1,000 km/s', '3,000 km/s', 'A'),
    ('Science', 'easy', 'What is H2O commonly known as?', 'Oxygen', 'Hydrogen', 'Water', 'Salt', 'C'),
    ('Science', 'medium', 'What is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Chloroplast', 'B'),
    ('Science', 'easy', 'Which planet is closest to the Sun?', 'Venus', 'Mercury', 'Earth', 'Mars', 'B'),
    ('Science', 'medium', 'What type of energy is stored in a battery?', 'Kinetic Energy', 'Thermal Energy', 'Chemical Energy', 'Nuclear Energy', 'C'),
    ('Science', 'easy', 'Which gas is most abundant in Earth''s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen', 'C'),
    ('Movies', 'easy', 'Which movie features the character Jack Sparrow?', 'Harry Potter', 'Pirates of the Caribbean', 'The Lord of the Rings', 'Avatar', 'B'),
    ('Movies', 'medium', 'Which movie won the Oscar for Best Picture in 2020?', '1917', 'Joker', 'Parasite', 'Ford v Ferrari', 'C'),
    ('Movies', 'easy', 'Which movie features dinosaurs brought back to life?', 'King Kong', 'Jurassic Park', 'Godzilla', 'Avatar', 'B'),
    ('Movies', 'medium', 'Who played the Joker in The Dark Knight (2008)?', 'Joaquin Phoenix', 'Jared Leto', 'Heath Ledger', 'Jack Nicholson', 'C'),
    ('Movies', 'easy', 'Which movie is about a sinking ship and a tragic love story?', 'Avatar', 'Titanic', 'Inception', 'Gladiator', 'B'),
    ('Movies', 'medium', 'Which film series features Frodo Baggins?', 'Harry Potter', 'The Hobbit', 'The Lord of the Rings', 'Star Wars', 'C'),
    ('Movies', 'easy', 'Which animated movie features a talking snowman named Olaf?', 'Moana', 'Frozen', 'Tangled', 'Coco', 'B'),
    ('General Knowledge', 'easy', 'Which is the largest mammal in the world?', 'Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus', 'B'),
    ('General Knowledge', 'medium', 'How many continents are there on Earth?', '5', '6', '7', '8', 'C'),
    ('General Knowledge', 'easy', 'Which bird is known for its ability to mimic sounds?', 'Parrot', 'Eagle', 'Sparrow', 'Pigeon', 'A'),
    ('General Knowledge', 'medium', 'Which is the largest organ in the human body?', 'Heart', 'Liver', 'Skin', 'Brain', 'C'),
    ('General Knowledge', 'easy', 'How many colors are there in a rainbow?', '5', '6', '7', '8', 'C'),
    ('General Knowledge', 'medium', 'Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'Thailand', 'South Korea', 'B'),
    ('General Knowledge', 'easy', 'What do bees produce?', 'Milk', 'Honey', 'Wax', 'Oil', 'B'),
    ('Technology', 'easy', 'What does CPU stand for?', 'Central Process Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Central Power Unit', 'B'),
    ('Technology', 'medium', 'Which company developed the Android operating system?', 'Apple', 'Microsoft', 'Google', 'IBM', 'C'),
    ('Technology', 'easy', 'What does RAM stand for?', 'Random Access Memory', 'Read Access Memory', 'Run Access Memory', 'Real Access Memory', 'A'),
    ('Technology', 'medium', 'Which programming language is primarily used for web page styling?', 'HTML', 'Python', 'CSS', 'C++', 'C'),
    ('Technology', 'easy', 'What does URL stand for?', 'Uniform Resource Locator', 'Universal Resource Link', 'Uniform Reference Link', 'Universal Reference Locator', 'A'),
    ('Technology', 'medium', 'Which company created the iPhone?', 'Samsung', 'Apple', 'Google', 'Microsoft', 'B'),
    ('Technology', 'easy', 'What is the brain of the computer?', 'RAM', 'Hard Drive', 'CPU', 'GPU', 'C'),
    ('Sports', 'easy', 'How many players are there in a football (soccer) team on the field?', '9', '10', '11', '12', 'C'),
    ('Sports', 'medium', 'Which country won the FIFA World Cup in 2018?', 'Germany', 'Brazil', 'France', 'Argentina', 'C'),
    ('Sports', 'easy', 'Which sport uses a racket and a shuttlecock?', 'Tennis', 'Badminton', 'Squash', 'Table Tennis', 'B'),
    ('Sports', 'medium', 'In cricket, how many runs are awarded for hitting the ball over the boundary without bouncing?', '4', '5', '6', '3', 'C'),
    ('Sports', 'easy', 'Which country is famous for sumo wrestling?', 'China', 'Japan', 'South Korea', 'Thailand', 'B'),
    ('Sports', 'medium', 'How many rings are there in the Olympic symbol?', '4', '5', '6', '7', 'B'),
    ('Sports', 'easy', 'Which sport is known as the ''king of sports''?', 'Cricket', 'Basketball', 'Football', 'Tennis', 'C'),
    ('Food', 'easy', 'What is the main ingredient in sushi?', 'Bread', 'Rice', 'Potato', 'Noodles', 'B'),
    ('Food', 'medium', 'Which country is famous for the dish ''Paella''?', 'Italy', 'Spain', 'France', 'Mexico', 'B'),
    ('Food', 'easy', 'Which fruit is known as the king of fruits in India?', 'Apple', 'Banana', 'Mango', 'Orange', 'C'),
    ('Food', 'medium', 'Which country is the origin of pizza?', 'France', 'Italy', 'USA', 'Greece', 'B'),
    ('Food', 'easy', 'What is tofu made from?', 'Milk', 'Soybeans', 'Wheat', 'Rice', 'B'),
    ('Food', 'medium', 'Which vitamin is primarily found in citrus fruits?', 'Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D', 'C'),
    ('Food', 'easy', 'What is the main ingredient in bread?', 'Rice', 'Flour', 'Corn', 'Oats', 'B')
) as q(category_name, difficulty, question_text, option_a, option_b, option_c, option_d, correct_answer)
join public.categories c on c.name = q.category_name
on conflict do nothing;
